/**
 * Autonomous Agent — Backend-Driven Architecture
 * 
 * v2: Decision engine runs on Cloudflare Workers Cron.
 * Frontend only manages:
 *   1. Starting/stopping the agent via backend API
 *   2. Pushing context snapshots to backend periodically
 *   3. Polling for messages generated by the backend
 *   4. Notifying backend when user replies
 * 
 * The local tick loop, probability gate, and LLM calls have been
 * removed — all decision logic now lives in csyos-workers/src/services/agentEngine.ts
 */

import { DB } from './db';
import { CharacterProfile } from '../types';
import { getBackendUrl, getUserId } from './backendClient';

// ═══════════════════════════════════════════════════════════════
//  Types (shared with backend)
// ═══════════════════════════════════════════════════════════════

export interface SecondaryApiConfig {
    baseUrl: string;
    apiKey: string;
    model: string;
}

export interface LLMDecision {
    action: 'none' | 'send' | 'call' | 'think';
    topic?: string;
    reason?: string;
    content?: string;
}

export interface AgentConfig {
    minIntervalMin: number;
    maxIntervalMin: number;
    cooldownHours: number;
    maxDailyActions: number;
    maxConsecutiveIgnored: number;
    baseProb: number;
    notificationsEnabled: boolean;
}

const AGENT_CONFIG_DEFAULTS: AgentConfig = {
    minIntervalMin: 15,
    maxIntervalMin: 40,
    cooldownHours: 2,
    maxDailyActions: 5,
    maxConsecutiveIgnored: 2,
    baseProb: 0.15,
    notificationsEnabled: true,
};

const AGENT_CONFIG_STORAGE_KEY = 'agent_config';

/** 读取用户配置，缺失项使用默认值 */
export function getAgentConfig(): AgentConfig {
    try {
        const raw = localStorage.getItem(AGENT_CONFIG_STORAGE_KEY);
        if (raw) {
            const parsed = JSON.parse(raw);
            return { ...AGENT_CONFIG_DEFAULTS, ...parsed };
        }
    } catch { /* ignore */ }
    return { ...AGENT_CONFIG_DEFAULTS };
}

/** 保存用户配置 */
export function saveAgentConfig(config: Partial<AgentConfig>): void {
    try {
        const current = getAgentConfig();
        const merged = { ...current, ...config };
        localStorage.setItem(AGENT_CONFIG_STORAGE_KEY, JSON.stringify(merged));
    } catch { /* ignore */ }
}

// ═══════════════════════════════════════════════════════════════
//  Backend API Client
// ═══════════════════════════════════════════════════════════════

function getHeaders(): Record<string, string> {
    return {
        'Content-Type': 'application/json',
        'Authorization': `Bearer change-me-to-a-random-string`,
        'X-User-Id': getUserId(),
    };
}

async function agentFetch(path: string, options: RequestInit = {}): Promise<any> {
    const baseUrl = getBackendUrl();
    if (!baseUrl) throw new Error('Backend URL not configured');

    const resp = await fetch(`${baseUrl}${path}`, {
        ...options,
        headers: { ...getHeaders(), ...(options.headers || {}) },
        signal: AbortSignal.timeout(15000),
    });

    if (!resp.ok) {
        const text = await resp.text().catch(() => '');
        throw new Error(`Agent API ${resp.status}: ${text.slice(0, 200)}`);
    }

    return resp.json();
}

// ═══════════════════════════════════════════════════════════════
//  Context Snapshot Builder
// ═══════════════════════════════════════════════════════════════

async function buildContextSnapshot(charId: string, char: CharacterProfile) {
    const now = Date.now();

    // 获取最近消息
    const recentMsgs = await DB.getRecentMessagesByCharId(charId, 20);

    // 计算沉默时长
    let lastUserMsgAt = 0;
    let lastAIMsgAt = 0;
    let lastAIMsgWasAutonomous = false;

    for (let i = recentMsgs.length - 1; i >= 0; i--) {
        const m = recentMsgs[i];
        if (m.role === 'user' && !lastUserMsgAt) lastUserMsgAt = m.timestamp;
        if (m.role === 'assistant' && !lastAIMsgAt) {
            lastAIMsgAt = m.timestamp;
            lastAIMsgWasAutonomous = m.metadata?.source === 'autonomous';
        }
    }

    // 获取用户名
    let userName = '用户';
    try {
        const userProfile = await DB.getUserProfile();
        if (userProfile?.name) userName = userProfile.name;
    } catch { /* ignore */ }

    // 获取可用表情包名称
    let emojiNames: string[] = [];
    try {
        const emojis = await DB.getEmojis();
        emojiNames = emojis.map(e => e.name).slice(0, 30); // Limit to 30 names
    } catch { /* ignore */ }

    // 荷尔蒙状态
    const moodState = (char.moodState as unknown as Record<string, number>) || null;

    // 人设摘要（截取前 2000 字）
    const charSystemPrompt = (char.systemPrompt || '').slice(0, 2000);
    const charPersonality = (char.description || '').slice(0, 300);

    // 精选高权重记忆
    let topMemory: string | undefined;
    try {
        const headers = await DB.getVectorMemoryHeaders(charId);
        if (headers && headers.length > 0) {
            const active = headers.filter(h => !h.deprecated);
            if (active.length > 0) {
                // 取 importance 最高的
                active.sort((a, b) => (b.importance || 5) - (a.importance || 5));
                const top = active[0];
                topMemory = `${top.title || ''}：${(top.content || '').slice(0, 80)}`;
            }
        }
    } catch { /* ignore */ }

    return {
        charId,
        charName: char.name,
        charSystemPrompt,
        charPersonality,
        userName,
        recentMessages: recentMsgs.map(m => ({
            role: m.role,
            content: m.content.slice(0, 500), // Limit per message
            timestamp: m.timestamp,
        })),
        moodState,
        lastUserMsgAt,
        lastAIMsgAt,
        lastAIMsgWasAutonomous,
        emojiNames,
        topMemory,
        updatedAt: now,
    };
}

// ═══════════════════════════════════════════════════════════════
//  BackendAgentManager — Frontend Orchestrator
// ═══════════════════════════════════════════════════════════════

export class BackendAgentManager {
    private pollTimer: ReturnType<typeof setInterval> | null = null;
    private contextTimer: ReturnType<typeof setInterval> | null = null;
    private stopped = false;
    private charId: string = '';
    private charRef: CharacterProfile | null = null;

    /**
     * 启动 Agent:
     *   1. 推送完整上下文到后端
     *   2. 调用 /api/agent/start
     *   3. 启动消息轮询 (30s) 和上下文推送 (5min)
     * 
     * @returns cleanup 函数
     */
    start(
        charId: string,
        char: CharacterProfile,
        secondaryApi: SecondaryApiConfig,
    ): () => void {
        this.stopped = false;
        this.charId = charId;
        this.charRef = char;

        const isDebug = localStorage.getItem('autonomous_debug') === 'true';

        // Async initialization
        (async () => {
            try {
                // 1. Build context snapshot
                const contextSnapshot = await buildContextSnapshot(charId, char);

                // 2. Get primary API config
                let mainApiConfig: SecondaryApiConfig | undefined;
                try {
                    const raw = localStorage.getItem('os_api_config');
                    if (raw) {
                        const cfg = JSON.parse(raw);
                        if (cfg.apiKey && cfg.baseUrl && cfg.model) {
                            mainApiConfig = {
                                baseUrl: cfg.baseUrl.replace(/\/+$/, ''),
                                apiKey: cfg.apiKey,
                                model: cfg.model,
                            };
                        }
                    }
                } catch { /* ignore */ }

                if (!mainApiConfig) {
                    console.warn('🤖 [Agent] No primary API config, agent will not generate messages');
                }

                // 3. Start agent on backend
                await agentFetch('/api/agent/start', {
                    method: 'POST',
                    body: JSON.stringify({
                        charId,
                        apiConfig: secondaryApi,
                        mainApiConfig,
                        contextSnapshot,
                        agentConfig: getAgentConfig(),
                    }),
                });

                console.log(`🤖 [Agent] Backend agent started for ${char.name}`);

                if (this.stopped) return;

                // 4. Start polling for messages (every 30s)
                this.pollTimer = setInterval(() => {
                    if (this.stopped) return;
                    this.pollMessages().catch(err => {
                        if (isDebug) console.warn('🤖 [Agent] Poll error:', err.message);
                    });
                }, 30000);

                // Also poll immediately after a short delay
                setTimeout(() => {
                    if (!this.stopped) this.pollMessages().catch(() => {});
                }, 10000);

                // 5. Push context updates every 5 minutes
                this.contextTimer = setInterval(() => {
                    if (this.stopped) return;
                    this.pushContext().catch(err => {
                        if (isDebug) console.warn('🤖 [Agent] Context push error:', err.message);
                    });
                }, 5 * 60 * 1000);

            } catch (err: any) {
                console.error('🤖 [Agent] Failed to start backend agent:', err.message);
            }
        })();

        return () => this.stop();
    }

    stop(): void {
        this.stopped = true;
        if (this.pollTimer) { clearInterval(this.pollTimer); this.pollTimer = null; }
        if (this.contextTimer) { clearInterval(this.contextTimer); this.contextTimer = null; }

        // Stop agent on backend (fire and forget)
        if (this.charId) {
            agentFetch('/api/agent/stop', {
                method: 'POST',
                body: JSON.stringify({ charId: this.charId }),
            }).catch(() => {});
        }

        console.log('🤖 [Agent] Stopped');
    }

    /**
     * Poll for backend-generated messages and write them to local DB
     * as scheduled messages (same pipeline as before).
     */
    async pollMessages(): Promise<void> {
        if (!this.charId) return;
        const isDebug = localStorage.getItem('autonomous_debug') === 'true';

        try {
            const data = await agentFetch(`/api/agent/messages?charId=${this.charId}`);
            const messages = data.messages || [];

            if (messages.length === 0) return;

            if (isDebug) {
                console.log(`🤖 [Agent] Polled ${messages.length} pending message(s)`);
            }

            const now = Date.now();
            for (let i = 0; i < messages.length; i++) {
                const msg = messages[i];
                const metadata = msg.metadata ? JSON.parse(msg.metadata) : {};

                await DB.saveScheduledMessage({
                    id: `backend-${msg.id}-${i}`,
                    charId: this.charId,
                    content: msg.content,
                    dueAt: now + i * 3000, // Stagger by 3s
                    createdAt: msg.created_at || now,
                    metadata: {
                        source: 'autonomous',
                        reason: metadata.reason,
                        fromBackend: true,
                    },
                });
            }

            console.log(`🤖 [Agent] Saved ${messages.length} backend message(s) to scheduled queue`);

        } catch (err: any) {
            // Silent failure — will retry on next poll
            if (localStorage.getItem('autonomous_debug') === 'true') {
                console.warn('🤖 [Agent] Poll failed:', err.message);
            }
        }
    }

    /**
     * Push fresh context snapshot to backend.
     * Called periodically (5 min) and before page unload.
     */
    async pushContext(): Promise<void> {
        if (!this.charId || !this.charRef) return;

        try {
            // Refresh character data
            let freshChar = this.charRef;
            try {
                const allChars = await DB.getAllCharacters();
                const found = allChars.find(c => c.id === this.charId);
                if (found) {
                    freshChar = found;
                    this.charRef = found;
                }
            } catch { /* use stale */ }

            const ctx = await buildContextSnapshot(this.charId, freshChar);
            await agentFetch('/api/agent/context', {
                method: 'POST',
                body: JSON.stringify(ctx),
            });

            if (localStorage.getItem('autonomous_debug') === 'true') {
                console.log('🤖 [Agent] Context pushed to backend');
            }
        } catch (err: any) {
            if (localStorage.getItem('autonomous_debug') === 'true') {
                console.warn('🤖 [Agent] Context push failed:', err.message);
            }
        }
    }

    /**
     * Notify backend that user sent a message → reset consecutiveIgnored.
     */
    static async notifyUserReplied(charId: string): Promise<void> {
        try {
            await agentFetch('/api/agent/user-replied', {
                method: 'POST',
                body: JSON.stringify({ charId }),
            });
        } catch { /* silent */ }
    }
}

// ═══════════════════════════════════════════════════════════════
//  Legacy compatibility — executeBackendDecision (kept for reference)
// ═══════════════════════════════════════════════════════════════

/**
 * @deprecated — Backend now handles message generation directly.
 * Kept for backward compatibility during transition.
 */
export async function executeBackendDecision(
    charId: string,
    char: CharacterProfile,
    decision: LLMDecision,
): Promise<void> {
    console.warn('🤖 [Agent] executeBackendDecision is deprecated — backend generates messages directly');
}
