import type { TheaterLocation } from '../types';
import { LOVE_SHOW_LOCATION_BG_BASE } from './loveshowLocations';

export const LOVE_SHOW_THEATER_LOCATIONS: TheaterLocation[] = [
    {
        id: 'ls_signal_balcony',
        name: '信号露台',
        nameEn: 'Signal Balcony',
        description: '小屋二层尽头的窄露台，能听见楼下工作人员压低声音对讲。栏杆边挂着几串暖色灯泡，风会把收音麦的防风毛套吹得轻轻晃动。这里离集体空间不远，却刚好能避开大部分镜头，适合两个人把刚才没说完的话补上。',
        tags: ['romantic', 'quiet', 'outdoor'],
        bgImage: `${LOVE_SHOW_LOCATION_BG_BASE}/theater-signal-balcony.jpg`,
        bgGradient: 'linear-gradient(135deg, #102033 0%, #27586a 48%, #f3bf73 100%)',
        isPreset: true,
        visitCount: 0,
    },
    {
        id: 'ls_late_store',
        name: '夜灯便利店',
        nameEn: 'Late Store',
        description: '节目组车程十分钟外的便利店，白色灯管把货架照得很亮。关东煮热气、冰柜声和自动门提示音混在一起，反而让沉默变得不尴尬。两个人可以并肩挑一瓶饮料，也可以在收银台前因为谁先开口而停顿很久。',
        tags: ['daily', 'indoor', 'quiet'],
        bgImage: `${LOVE_SHOW_LOCATION_BG_BASE}/theater-late-store.jpg`,
        bgGradient: 'linear-gradient(135deg, #f7f5df 0%, #8ed1bd 50%, #1b6b76 100%)',
        isPreset: true,
        visitCount: 0,
    },
    {
        id: 'ls_observation_booth',
        name: '单采间门外',
        nameEn: 'Interview Hall',
        description: '单采间外的走廊很窄，墙面贴着隔音软包，红色录制灯亮起时所有人都会下意识放轻声音。这里适合偶遇刚结束采访的嘉宾，情绪还没完全收回去，嘴硬、试探和突然的坦白都更容易发生。',
        tags: ['quiet', 'indoor'],
        bgImage: `${LOVE_SHOW_LOCATION_BG_BASE}/theater-interview-hall.jpg`,
        bgGradient: 'linear-gradient(135deg, #2a1b2e 0%, #75516d 52%, #e0a6a2 100%)',
        isPreset: true,
        visitCount: 0,
    },
    {
        id: 'ls_greenhouse',
        name: '玻璃花房',
        nameEn: 'Glass House',
        description: '小屋后院临时搭出的玻璃花房，白天会有很强的自然光，夜里只剩几盏小射灯。水雾机让叶片上挂着细小水珠，镜头拍出来像某种不真实的滤镜。适合克制暧昧，也适合三人片段里的视线错开。',
        tags: ['romantic', 'quiet', 'indoor'],
        bgImage: `${LOVE_SHOW_LOCATION_BG_BASE}/theater-glass-house.jpg`,
        bgGradient: 'linear-gradient(135deg, #17382f 0%, #7aa889 52%, #f3d7b0 100%)',
        isPreset: true,
        visitCount: 0,
    },
    {
        id: 'ls_kitchen_island',
        name: '小屋中岛台',
        nameEn: 'Kitchen Island',
        description: '晚饭后的开放式厨房，水槽边还有没擦干的玻璃杯，中岛台上放着节目组留下的任务卡。这里并不私密，随时可能有人经过，所以每一句话都要藏一半。适合把日常照顾拍成心动细节。',
        tags: ['daily', 'indoor'],
        bgImage: `${LOVE_SHOW_LOCATION_BG_BASE}/theater-kitchen-island.jpg`,
        bgGradient: 'linear-gradient(135deg, #392820 0%, #a97352 54%, #f1c98b 100%)',
        isPreset: true,
        visitCount: 0,
    },
    {
        id: 'ls_rooftop_laundry',
        name: '天台晾衣区',
        nameEn: 'Rooftop Lines',
        description: '顶楼角落拉着几根晾衣绳，白衬衫和毛巾被风吹得挡住半个镜头。远处城市灯光很密，近处只有风声和脚步声。适合一个人主动靠近，另一个人用整理衣架掩饰紧张。',
        tags: ['romantic', 'outdoor', 'quiet'],
        bgImage: `${LOVE_SHOW_LOCATION_BG_BASE}/theater-rooftop-lines.jpg`,
        bgGradient: 'linear-gradient(135deg, #182233 0%, #465f8e 50%, #c9b7d8 100%)',
        isPreset: true,
        visitCount: 0,
    },
    {
        id: 'ls_aquarium_tunnel',
        name: '蓝光水族馆',
        nameEn: 'Blue Tunnel',
        description: '闭馆后的水族馆隧道，头顶有鱼群慢慢游过，蓝色光线会让每个人的表情都显得更安静。说话声在玻璃里有一点回音，适合非常近的并肩，也适合三人之间微妙的站位变化。',
        tags: ['romantic', 'indoor', 'quiet'],
        bgImage: `${LOVE_SHOW_LOCATION_BG_BASE}/theater-blue-tunnel.jpg`,
        bgGradient: 'linear-gradient(135deg, #051d36 0%, #0d7c91 48%, #8be0d7 100%)',
        isPreset: true,
        visitCount: 0,
    },
    {
        id: 'ls_arcade_corner',
        name: '街机角落',
        nameEn: 'Arcade Corner',
        description: '商场角落的旧街机区，投币口有磨损，按键声音很清脆。这里比正式约会地点更像临时逃跑，适合借游戏输赢说真话，也适合两位嘉宾用玩笑把竞争藏起来。',
        tags: ['daily', 'crowded', 'indoor'],
        bgImage: `${LOVE_SHOW_LOCATION_BG_BASE}/theater-arcade-corner.jpg`,
        bgGradient: 'linear-gradient(135deg, #1c1238 0%, #c1427a 48%, #ffcb66 100%)',
        isPreset: true,
        visitCount: 0,
    },
    {
        id: 'ls_bookstore_window',
        name: '旧书店橱窗',
        nameEn: 'Book Window',
        description: '街边旧书店快打烊时，老板把门口小灯留着。橱窗里摆着节目同款拍立得，书脊上有褪色的手写价格。适合慢节奏的试探，谁先推荐一本书，谁就先暴露一点心事。',
        tags: ['quiet', 'indoor', 'daily'],
        bgImage: `${LOVE_SHOW_LOCATION_BG_BASE}/theater-book-window.jpg`,
        bgGradient: 'linear-gradient(135deg, #38291d 0%, #8d7151 52%, #e8cfa3 100%)',
        isPreset: true,
        visitCount: 0,
    },
    {
        id: 'ls_rain_bus_stop',
        name: '雨棚车站',
        nameEn: 'Rain Stop',
        description: '临时外景结束后下起小雨，节目车还没到，只有车站雨棚能躲。地面积水反光，远处车灯一闪一闪。适合一把伞、一次靠近，也适合三人片段里谁把位置让给你。',
        tags: ['romantic', 'outdoor', 'quiet'],
        bgImage: `${LOVE_SHOW_LOCATION_BG_BASE}/theater-rain-stop.jpg`,
        bgGradient: 'linear-gradient(135deg, #203041 0%, #6e8795 50%, #d6c7aa 100%)',
        isPreset: true,
        visitCount: 0,
    },
    {
        id: 'ls_photo_wall',
        name: '心动照片墙',
        nameEn: 'Photo Wall',
        description: '小屋一楼的照片墙贴着这几天的剧照和空白拍立得，旁边放着银色马克笔。每个人经过都会看一眼，却很少停留太久。适合让用户选一张照片，也适合嘉宾借一张照片问出真正想问的话。',
        tags: ['daily', 'indoor'],
        bgImage: `${LOVE_SHOW_LOCATION_BG_BASE}/theater-photo-wall.jpg`,
        bgGradient: 'linear-gradient(135deg, #2a2d34 0%, #b77b75 48%, #f5dfc7 100%)',
        isPreset: true,
        visitCount: 0,
    },
    {
        id: 'ls_morning_pier',
        name: '清晨栈桥',
        nameEn: 'Morning Pier',
        description: '海边外景的清晨栈桥，工作人员还在调机位，木板上有一层薄薄水汽。太阳刚升起，风有点冷，说话会自然放慢。适合不急着推进关系的片段，让心动藏在陪伴里。',
        tags: ['romantic', 'outdoor', 'quiet'],
        bgImage: `${LOVE_SHOW_LOCATION_BG_BASE}/theater-morning-pier.jpg`,
        bgGradient: 'linear-gradient(135deg, #31506b 0%, #8eb8bc 50%, #ffd39a 100%)',
        isPreset: true,
        visitCount: 0,
    },
    {
        id: 'ls_karaoke_backroom',
        name: '练歌房后台',
        nameEn: 'Backstage Room',
        description: '分组任务前的练歌房后台，隔壁传来伴奏声，桌上散着歌词纸和矿泉水。这里适合紧张前的互相打气，也适合一个嘉宾先开口、另一个嘉宾在门口听见半句。',
        tags: ['indoor', 'daily', 'crowded'],
        bgImage: `${LOVE_SHOW_LOCATION_BG_BASE}/theater-backstage-room.jpg`,
        bgGradient: 'linear-gradient(135deg, #24122d 0%, #8d3f73 45%, #f0b36b 100%)',
        isPreset: true,
        visitCount: 0,
    },
    {
        id: 'ls_secret_projection',
        name: '放映小厅',
        nameEn: 'Screening Room',
        description: '节目组临时搭的小放映厅，幕布上会播放当天未公开片段。座位只有三排，灯一暗下来，任何呼吸和转头都被放大。适合观看回放后的单独沉默，也适合三人片段里的公开误读。',
        tags: ['romantic', 'indoor', 'quiet'],
        bgImage: `${LOVE_SHOW_LOCATION_BG_BASE}/theater-screening-room.jpg`,
        bgGradient: 'linear-gradient(135deg, #171923 0%, #5a4a71 52%, #d4a373 100%)',
        isPreset: true,
        visitCount: 0,
    },
    {
        id: 'ls_makeup_mirror',
        name: '补妆镜前',
        nameEn: 'Mirror Corner',
        description: '录制间隙的补妆角，镜前一圈灯泡很亮，桌上有散粉刷、夹子和没喝完的水。这里适合极短的近距离互动，像一句压低声音的提醒，或一个被镜子反射出来的眼神。',
        tags: ['indoor', 'quiet'],
        bgImage: `${LOVE_SHOW_LOCATION_BG_BASE}/theater-mirror-corner.jpg`,
        bgGradient: 'linear-gradient(135deg, #35202c 0%, #b76e79 50%, #ffe1d6 100%)',
        isPreset: true,
        visitCount: 0,
    },
];

export function getLoveShowTheaterLocations(): TheaterLocation[] {
    return LOVE_SHOW_THEATER_LOCATIONS.map(location => ({ ...location, visitCount: 0, lastVisitTime: undefined }));
}

export function pickLoveShowTheaterLocationId(seed: string): string {
    if (LOVE_SHOW_THEATER_LOCATIONS.length === 0) return '';
    let hash = 0;
    for (let index = 0; index < seed.length; index += 1) {
        hash = (hash * 33 + seed.charCodeAt(index)) >>> 0;
    }
    return LOVE_SHOW_THEATER_LOCATIONS[hash % LOVE_SHOW_THEATER_LOCATIONS.length].id;
}
