L=[];a=L.append
a('                {/* \u2500\u2500 WORKSHOP TAB \u2500\u2500 */}')
a("                {activeTab === 'workshop' && (")
a('                    <div className="flex-1 overflow-y-auto no-scrollbar relative" style={{ background: \'linear-gradient(175deg, #0C0B0F 0%, #111015 45%, #0D0C11 100%)\' }}>')
a('                        <div className="absolute inset-0 pointer-events-none overflow-hidden select-none">')
a('                            <img src="/images/collage/mood-collage.png" alt="" className="absolute -top-6 -right-10 w-72 opacity-[0.03] mix-blend-screen" style={{ filter: \'invert(1)\', transform: \'rotate(8deg)\' }} />')
a('                            <img src="/images/collage/flower-cosmos.png" alt="" className="absolute top-[16%] -left-14 w-44 opacity-[0.04] mix-blend-screen" style={{ filter: \'invert(1)\', transform: \'rotate(-25deg)\' }} />')
a('                            <img src="/images/collage/butterfly-sparkle.png" alt="" className="absolute bottom-[6%] -right-10 w-56 opacity-[0.035] mix-blend-screen" style={{ filter: \'invert(1)\', transform: \'rotate(15deg)\' }} />')
a('                        </div>')
a('                        <div className="relative z-10 px-5 pt-16 pb-20">')
a('                            <div className="text-center mb-2 relative">')
a('                                <div className="absolute top-0 right-1 w-9 h-11 border border-dashed border-white/[0.04] rounded-sm flex flex-col items-center justify-center gap-0.5 pointer-events-none select-none">')
a('                                    <div className="w-5 h-5 rounded-full border border-white/[0.03]" />')
a('                                    <span className="text-[4px] text-white/[0.05] tracking-widest font-mono">POST</span>')
a('                                </div>')
a('                                <h2 className="text-[36px] font-bold text-white/80 tracking-[0.5em] leading-none" style={{ fontFamily: "\'Ma Shan Zheng\', \'Noto Serif SC\', serif" }}>\u62FE \u5FF5</h2>')
a('                                <p className="text-[9px] text-white/20 mt-3 tracking-[0.25em] italic leading-relaxed" style={{ fontFamily: "\'Noto Serif SC\', serif" }}>\u6709\u4E9B\u4E8B\u4E0D\u8BF4\uFF0C\u5FC3\u91CC\u4E5F\u8BB0\u5F97\u4F4F</p>')
a('                            </div>')
a('                            <div className="flex justify-center gap-2 overflow-x-auto no-scrollbar mt-6 mb-10 -mx-5 px-5">')
a('                                {characters.map(c => (')
a("                                    <button key={c.id} onClick={() => { setSelectedCharId(c.id); haptic.light(); }}")
a("                                        className={`shrink-0 flex items-center gap-1.5 px-3.5 py-2 rounded-full text-[10px] font-medium transition-all ${selectedCharId === c.id ? 'bg-white/90 text-[#1E1E20] shadow-[0_4px_20px_rgba(255,255,255,0.12)]' : 'bg-white/[0.04] text-white/35 border border-white/[0.06] hover:bg-white/[0.08]'}`}>")
a('                                        <img src={c.avatar} alt={c.name} className="w-4 h-4 rounded-full object-cover" />')
a('                                        {c.name}')
a('                                    </button>')
a('                                ))}')
a('                            </div>')
a('                            <div className="relative">')
a('                                <span className="absolute -top-3 right-4 text-[8px] text-white/[0.06] italic tracking-[0.15em] select-none pointer-events-none" style={{ fontFamily: "Georgia, serif", transform: \'rotate(2deg)\' }}>Good night</span>')
a('                                <span className="absolute top-[44%] -left-1 text-[7px] text-white/[0.05] tracking-[0.3em] select-none pointer-events-none" style={{ fontFamily: "Georgia, serif", writingMode: \'vertical-rl\', transform: \'rotate(180deg)\' }}>falls.</span>')
a('                                <span className="absolute bottom-[18%] right-2 text-[7px] text-white/[0.04] italic tracking-[0.2em] select-none pointer-events-none" style={{ fontFamily: "\'Noto Serif SC\', serif", transform: \'rotate(-1deg)\' }}>\u53EA\u662F\u88AB\u65F6\u95F4\u6E29\u67D4\u6536\u85CF</span>')
a('                                <div className="relative mb-10" style={{ transform: \'rotate(-1.2deg)\', marginLeft: \'6%\', marginRight: \'1%\' }}>')
a('                                    <span className="absolute -top-6 -left-1 text-[56px] font-extralight text-white/[0.04] select-none pointer-events-none z-0" style={{ fontFamily: "\'Ma Shan Zheng\', serif", letterSpacing: \'0.05em\' }}>01</span>')
a('                                    <div className="absolute -top-1.5 right-10 w-14 h-3.5 rounded-[1px] z-20 pointer-events-none" style={{ background: \'linear-gradient(90deg, transparent 0%, rgba(255,255,255,0.05) 15%, rgba(255,255,255,0.07) 50%, rgba(255,255,255,0.05) 85%, transparent 100%)\', transform: \'rotate(4deg)\' }} />')
a('                                    <div className="bg-[#FFFBF7]/[0.94] backdrop-blur-xl rounded-2xl border border-white/25 overflow-hidden shadow-[0_8px_40px_rgba(0,0,0,0.55),0_2px_10px_rgba(0,0,0,0.35)] relative z-10">')
a('                                        <div className="flex items-stretch gap-0 p-0 min-h-[140px]">')
a('                                            <div className="w-[38%] shrink-0 overflow-hidden"><img src="/images/workshop-birds.jpg" alt="" className="w-full h-full object-cover" style={{ filter: \'brightness(0.88) contrast(1.08)\' }} /></div>')
a('                                            <div className="flex-1 flex flex-col justify-between p-4 min-w-0">')
a('                                                <div><h4 className="text-[13px] font-bold text-[#1E1C22] tracking-wide mb-1.5" style={{ fontFamily: "\'Noto Serif SC\', serif" }}>\u65F6\u5149\u7F16\u7EC7</h4><p className="text-[10px] text-[#6B6675] leading-[1.7]">\u628A\u6BCF\u4E00\u6B21\u76F8\u9047\u4E32\u6210\u65F6\u95F4\u8F74\u4E0A\u7684\u73E0\u5B50\uFF0C\u8BA9\u524D\u56E0\u540E\u679C\u81EA\u7136\u76F8\u8FDE\u3002</p></div>')
a("                                                <div className=\"flex justify-end mt-2\"><button onClick={() => { setShowConfirm('temporal'); haptic.light(); }} disabled={backfilling || !selectedCharId} className=\"px-4 py-1.5 rounded-full text-[10px] font-semibold text-white bg-[#2A2830] hover:bg-[#1E1C22] active:scale-[0.97] transition-all disabled:opacity-40\">{backfilling ? '\u7F16\u7EC7\u4E2D\u2026' : '\u7EBA\u7EBF \u2192'}</button></div>")
a('                                            </div>')
a('                                        </div>')
a('                                        {backfillResult && !backfilling && (<div className="mx-5 mb-5 pt-4 border-t border-[#EEEDF0]"><ResultCard title="\u7F16\u7EC7\u62A5\u544A" isDryRun={false} stats={[{value:backfillResult.totals?.memories??0,label:\'\u8DE8\u8D8A\u7247\u6BB5\'},{value:backfillResult.totals?.linksCreated??0,label:\'\u4E1D\u7EBF\u6210\u578B\'},{value:backfillResult.totals?.edgesCreated??0,label:\'\u56E0\u679C\u843D\u5B9A\'}]} items={[]} note={undefined} /></div>)}')
a('                                    </div>')
a('                                    <img src="/images/collage/clock-airmail.png" alt="" className="absolute -bottom-10 -right-3 w-28 opacity-[0.07] mix-blend-screen pointer-events-none z-0" style={{ filter: \'invert(1)\', transform: \'rotate(10deg)\' }} />')
a('                                </div>')
a('                                <div className="relative mb-10" style={{ transform: \'rotate(0.8deg)\', marginRight: \'6%\', marginLeft: \'1%\' }}>')
a('                                    <span className="absolute -top-6 -left-1 text-[56px] font-extralight text-white/[0.04] select-none pointer-events-none z-0" style={{ fontFamily: "\'Ma Shan Zheng\', serif", letterSpacing: \'0.05em\' }}>02</span>')
a('                                    <div className="absolute -bottom-1 left-8 w-12 h-3.5 rounded-[1px] z-20 pointer-events-none" style={{ background: \'linear-gradient(90deg, transparent 0%, rgba(255,255,255,0.04) 15%, rgba(255,255,255,0.06) 50%, rgba(255,255,255,0.04) 85%, transparent 100%)\', transform: \'rotate(-3deg)\' }} />')
a('                                    <img src="/images/collage/lace-butterfly-dark.png" alt="" className="absolute -top-14 -right-5 w-24 opacity-[0.06] mix-blend-screen pointer-events-none z-0" style={{ filter: \'invert(1)\', transform: \'rotate(-8deg)\' }} />')
a('                                    <div className="bg-[#FFFBF7]/[0.94] backdrop-blur-xl rounded-2xl border border-white/25 overflow-hidden shadow-[0_8px_40px_rgba(0,0,0,0.55),0_2px_10px_rgba(0,0,0,0.35)] relative z-10">')
a('                                        <div className="flex items-stretch gap-0 p-0 min-h-[140px]">')
a('                                            <div className="w-[38%] shrink-0 overflow-hidden"><img src="/images/workshop-window.jpg" alt="" className="w-full h-full object-cover" style={{ filter: \'brightness(0.88) contrast(1.08)\' }} /></div>')
a('                                            <div className="flex-1 flex flex-col justify-between p-4 min-w-0">')
a('                                                <div><h4 className="text-[13px] font-bold text-[#1E1C22] tracking-wide mb-1.5" style={{ fontFamily: "\'Noto Serif SC\', serif" }}>\u5FC3\u610F\u63D0\u53D6</h4><p className="text-[10px] text-[#6B6675] leading-[1.7]">\u6355\u6349\u8BDD\u8BED\u95F4\u5FAE\u5999\u7684\u60C5\u611F\u5171\u632F\uFF0C\u627E\u5230\u90A3\u4E9B\u4E0D\u66FE\u8BF4\u51FA\u53E3\u7684\u9ED8\u5951\u3002</p></div>')
a('                                                <div className="flex justify-end gap-1.5 mt-2 flex-wrap">')
a('                                                    {queueStatus?.running && queueStatus.canAbort && !queueStatus.aborted && (<button onClick={handleAbortSemantic} className="px-3 py-1.5 rounded-full text-[10px] font-medium text-[#C48070] border border-[#E0DDE4] hover:bg-[#F5F4F6] transition-all">\u6682\u505C</button>)}')
a("                                                    <button onClick={() => { setShowConfirm('semanticRebuild'); haptic.light(); }} disabled={semanticRebuilding || !selectedCharId} className=\"px-3 py-1.5 rounded-full text-[10px] font-medium text-[#6B6675] border border-[#E0DDE4] hover:bg-[#F5F4F6] active:scale-[0.97] transition-all disabled:opacity-40\">\u5168\u90E8\u91CD\u6765</button>")
a("                                                    <button onClick={() => { setShowConfirm('semantic'); haptic.light(); }} disabled={semanticRunning || !selectedCharId} className=\"px-4 py-1.5 rounded-full text-[10px] font-semibold text-white bg-[#2A2830] hover:bg-[#1E1C22] active:scale-[0.97] transition-all disabled:opacity-40\">{semanticRunning && !semanticRebuilding ? '\u611F\u5E94\u4E2D\u2026' : '\u6267\u884C \u2192'}</button>")
a('                                                </div></div></div></div></div>')
a('                                <div className="relative mb-6" style={{ transform: \'rotate(-0.5deg)\', marginLeft: \'4%\', marginRight: \'3%\' }}>')
a('                                    <span className="absolute -top-6 -left-1 text-[56px] font-extralight text-white/[0.04] select-none pointer-events-none z-0" style={{ fontFamily: "\'Ma Shan Zheng\', serif", letterSpacing: \'0.05em\' }}>03</span>')
a('                                    <div className="absolute -top-1 left-6 w-16 h-3.5 rounded-[1px] z-20 pointer-events-none" style={{ background: \'linear-gradient(90deg, transparent 0%, rgba(255,255,255,0.04) 15%, rgba(255,255,255,0.06) 50%, rgba(255,255,255,0.04) 85%, transparent 100%)\', transform: \'rotate(-2deg)\' }} />')
a('                                    <div className="bg-[#FFFBF7]/[0.94] backdrop-blur-xl rounded-2xl border border-white/25 overflow-hidden shadow-[0_8px_40px_rgba(0,0,0,0.55),0_2px_10px_rgba(0,0,0,0.35)] relative z-10">')
a('                                        <div className="flex items-stretch gap-0 p-0 min-h-[140px]">')
a('                                            <div className="w-[38%] shrink-0 overflow-hidden"><img src="/images/workshop-papers.jpg" alt="" className="w-full h-full object-cover" style={{ filter: \'brightness(0.88) contrast(1.08)\' }} /></div>')
a('                                            <div className="flex-1 flex flex-col justify-between p-4 min-w-0">')
a('                                                <div><h4 className="text-[13px] font-bold text-[#1E1C22] tracking-wide mb-1.5" style={{ fontFamily: "\'Noto Serif SC\', serif" }}>\u56DE\u5FC6\u7ED3\u6676</h4><p className="text-[10px] text-[#6B6675] leading-[1.7]">\u5C06\u96F6\u788E\u7684\u65E5\u5E38\u6C89\u6DC0\u6210\u4E00\u679A\u679A\u6052\u4E45\u7684\u5370\u8C61\uFF0C\u50CF\u7425\u73C0\u5C01\u4F4F\u5149\u9634\u3002</p></div>')
a('                                                <div className="flex justify-end gap-1.5 mt-2">')
a("                                                    <button onClick={() => { setShowConfirm('distillRebuild'); haptic.light(); }} disabled={distillRebuilding || !selectedCharId} className=\"px-3 py-1.5 rounded-full text-[10px] font-medium text-[#6B6675] border border-[#E0DDE4] hover:bg-[#F5F4F6] active:scale-[0.97] transition-all disabled:opacity-40\">\u6253\u7891\u91CD\u805A</button>")
a("                                                    <button onClick={() => { setShowConfirm('distill'); haptic.light(); }} disabled={distilling || !selectedCharId} className=\"px-4 py-1.5 rounded-full text-[10px] font-semibold text-white bg-[#2A2830] hover:bg-[#1E1C22] active:scale-[0.97] transition-all disabled:opacity-40\">{distilling ? '\u7ED3\u6676\u4E2D\u2026' : '\u8403\u53D6\u5370\u8C61 \u2192'}</button>")
a('                                                </div></div></div>')
a('                                        {distillResult && !distilling && (distillResult.l1Created > 0 || distillResult.l1Merged > 0) && (<div className="mx-5 mb-5 pt-4 border-t border-[#EEEDF0]"><ResultCard title="\u7ED3\u6676\u62A5\u544A" isDryRun={false} stats={[{value:distillResult.l1Created,label:\'L1 \u65B0\u5EFA\'},{value:distillResult.l1Merged,label:\'\u5408\u5E76\'},{value:distillResult.l0Linked,label:\'L0 \u5173\u8054\'}]} items={[]} note={undefined} /></div>)}')
a('                                    </div>')
a('                                    <img src="/images/collage/lace-ribbon-butterfly.png" alt="" className="absolute -bottom-14 -left-3 w-32 opacity-[0.06] mix-blend-screen pointer-events-none z-0" style={{ filter: \'invert(1)\', transform: \'rotate(-5deg)\' }} />')
a('                                </div>')
a('                                {queueStatus && (<div className="bg-white/[0.05] backdrop-blur-xl border border-white/[0.06] text-white/90 rounded-2xl p-5 overflow-hidden mt-4" style={{ transform: \'rotate(0.3deg)\' }}>')
a('                                    <div className="flex justify-between items-center mb-3"><h4 className="text-[12px] font-semibold tracking-wider flex items-center gap-2"><span className={`w-1.5 h-1.5 rounded-full ${queueStatus.running ? \'bg-emerald-400 animate-pulse\' : \'bg-white/30\'}`} />\u5904\u7406\u8FDB\u5EA6</h4><span className="text-[9px] text-white/40 font-mono">{queueStatus.aborted ? \'\u5DF2\u6682\u505C\' : queueStatus.running ? \'\u8FDB\u884C\u4E2D\' : \'\u5B8C\u6210\'}</span></div>')
a('                                    <div className="relative h-1 bg-white/10 rounded-full overflow-hidden mb-4"><div className="absolute top-0 left-0 h-full bg-white/50 rounded-full transition-all duration-500" style={{ width: `${queueStatus.total > 0 ? ((queueStatus.done + queueStatus.errors) / queueStatus.total) * 100 : 0}%` }} /></div>')
a('                                    <div className="flex justify-between text-[10px] text-white/50"><span>{queueStatus.done} / {queueStatus.total} \u5B8C\u6210</span>{queueStatus.errors > 0 && <span className="text-rose-300">{queueStatus.errors} \u5F02\u5E38</span>}{(queueStatus.totalRelations ?? 0) > 0 && <span>{queueStatus.totalRelations} \u5173\u8054</span>}</div>')
a('                                    {queueStatus.lastError && (<div className="mt-3 text-[9px] text-rose-300/80 font-mono break-words bg-white/5 p-2 rounded-lg">{queueStatus.lastError}</div>)}')
a('                                </div>)}')
a('                            </div>')
a('                            <div className="mt-20 mb-4 text-center"><div className="w-10 h-px bg-white/[0.06] mx-auto mb-5" /><p className="text-[8px] text-white/[0.1] tracking-[0.3em] italic leading-loose" style={{ fontFamily: "\'Noto Serif SC\', serif" }}>\u8BB0\u5FC6\u4ECE\u4E0D\u892A\u8272\uFF0C\u53EA\u662F\u88AB\u65F6\u95F4\u6E29\u67D4\u6536\u85CF\u3002</p><p className="text-[7px] text-white/[0.05] tracking-[0.15em] mt-3 italic" style={{ fontFamily: "Georgia, serif" }}>Cognitive Engine</p></div>')
a('                        </div></div>')
a('                )}')
c='\n'.join(L)+'\n'
with open('apps/workshop-new.txt','w',encoding='utf-8') as f:
    f.write(c)
print(f'OK {len(L)} lines {len(c)} bytes')
